\mainmatter

# Period 1: London---Birth of a New Order (1558--1659)

## John Lyly: London the Ideal City

From ``Euphues' Glass for Europe," in _Euphues and His England_ (1580)

选自约翰·李利《尤菲绮斯和他的英格兰》

## \index{Lupton, Donald}Donald Lupton: London Bridge {#lupton}

From ``London Bridge," in _London and the Country Carbonadoed and Quartered_ (1632), Part 1, No. 4

## \index{Herrick, Robert}Robert Herrick Laments Leaving His Native London {#herrick}

``His Tears to Thamesis," in _Hesperides_ (1648) (written 1629)

选自罗伯特·赫里克《金苹果园》

|    I send, I send here my supremest kiss
|    To thee my silver-footed Thamesis. [_the Thames_]
|    No more shall I reiterate^[**reiterate**: go up and down.] thy Strand,^[**Strand**: the river shores; the street known as the **Strand**, joining London and Westminster.]
|    Whereon so many stately structures stand;
|    Nor in the summer's sweeter evenings go
|    To bathe in thee, as thousand others do.
|    No more shall I along thy crystal glide
|    In barge with boughs and rushes beautified,
|    With soft-smooth virgins (for our chaste disport)
|    To Richmond, Kingston, and to Hampton Court.
|    Never again shall I with finny oar^[**finny oar**: fin-shaped oar.]
|    Put from, or draw unto the faithful shore;
|    And landing here, or safely landing there,
|    Make way to my beloved Westminster,^[**Westminster**: Herrick probably lived here before his departure.]
|    Or to the golden Cheapside^[**golden Cheapside**: **Cheapside** was the goldsmith's district.], where the earth
|    Of Julia Herrick gave to me my birth.^[**the earth ... birth**: Herrick's mother died shortly before he left for Devon; hence the mention of the **earth** of her grave.]
|    May all clean nymphs and curious water dames,
|    With swan-like state, float up and down thy streams;
|    No drought upon thy wanton waters fall
|    To make them lean and languishing at all.
|    No ruffling winds come hither to disease^[**disease**: disturb, make uneasy; infect.]
|    Thy pure and silver-wristed Naiades.
|    Keep up your state, ye streams; and as ye spring,
|    Never make sick your banks by surfeiting.
|    Grow young with tides, and though I see ye never,
|    Receive this vow: ``so fare-ye-well forever."

## \index{Herrick, Robert}Herrick's Joyful Return to London

``His Return to London," in _Hesperides_ (1648)

见 \@ref(herrick)

|    From the dull cónfines of the drooping west,
|    To see the day spring from the pregnant east,
|    Ravish'd in spirit, I come, nay more, I fly
|    To thee, blest place of my nativity!
|    Thus, thus with hallow'd foot I touch the ground,
|    With thousand blessings by thy fortune crown'd.
|    O fruitful Genius! that bestowest here
|    An everlasting plenty, year by year.
|    O Place! O People! Manners! framed to please
|    All Nations, Customs, Kindreds, Languages!
|    I am a freeborn Roman^[Alluding to Acts 22:28.] ; suffer then,
|    That I amongst you live a Citizen.
|    London my home is, though by hard fate sent
|    Into a long and irksome banishment;
|    Yet since call'd back, henceforward let me be,
|    O native country, repossess'd by thee!
|    For, rather than I'll to the west return,^[**to the west return**: Herrick's parish was of course in the **west**, but so is the setting sun, traditionally associated with death.]
|    I'll beg of thee first here to have mine urn.
|    Weak I am grown, and must in short time fall;
|    Give thou my sacred relics burial.^[**Weak ... burial**: Herrick was in fact only 56; he did not die in London. He returned to Dean Prior when his living was restored in 1662 and was buried there on his death in 1674.]

## John Webster: The Decrepitude of Some London Buildings

From _Westward Ho_ (1607), Act 2, Sc. 1

\begin{drama}
\speaker{Honeysuckle}[...W]hat news flutters abroad? Do jackdaws dung the top of Paul's steeple still?\footnote{\textbf{Paul's steeple}: old St Paul's Cathedral lost its steeple to lightning in 1561.}
\speaker{Justiniano}The more is the pity if any daws do come into the temple, as I fear they do.
\speaker{Honeysuckle}They say Charing Cross is fallen down since I went to Rochelle\footnote{\textbf{Rochelle}: La Rochelle, a prosperous Huguenot (Protestant) city in SW France.};
but that's no such wonder: 'twas old, and stood awry, as most part of the
world can tell. And though it lack under-propping, yet, like great fellows at a
wrestling, when their heels are once flying up no man will save 'em: down they
fall, and there let them lie, though they were bigger than the Guard. Charing
Cross was old, and old things must shrink as well as new Northern cloth.\footnote{\textbf{new \ldots{} cloth}: Cheating tailors stretched their \textbf{cloth} tightly on its frame so that it shrank when it became wet.}
\speaker{Justiniano}Your worship is in the right way verily: they must so, but a number
of better things between Westminster and TempleBar,\footnote{\textbf{Westminster \ldots{} Temple Bar}: the area between \textbf{Westminster} Hall and the Inns of Court [\ref{lamb}, n.93] near \textbf{Temple Bar} frequented by those of the legal profession.} both of a worshipful
and honourable erection, are fallen to decay and have suffered putrefaction
since Charing fell that were not of half so long-standing as the poor wrynecked monument.
\end{drama}

约翰·韦伯斯特

## John Donne: The Lively Streets of London

Satire I, in _Poems._ 2nd ed. (1635) (first pub. 1633; written c. 1593--1594)

多恩的诗

|    Away, thou changeling motley humourist!^[**changeling**: foolish; inconstant; **motley**: incongruous, ill-sorted; dressed like a court jester; **humourist**: whimsical, unstable person.]
|    Leave me, and in this standing wooden chest,^[**standing wooden chest**: (1) study; (2) coffin.]
|    Consorted with these few books, let me lie
|    In prison, and here be coffin'd when I die.
|    Here are God's conduits, grave divines^[**God's ... divines**: theologians, who convey (like a conduit) knowledge of God to men.]; and here
|    Nature's secretary, the Philosopher^[**Nature's secretary, the philosopher**: two epithets commonly applied to Aristotle.];
|    And wily statesmen, which teach how to tie
|    The sinews of a city's mystic body^[38];
|    Here gath'ring^[39] chroniclers, and by them stand
|    Giddy fantastic poets of each land.
|    Shall I leave all this constant company,
|    And follow headlong wild uncertain thee?
|    First, swear by thy best love, here, in earnest
|    (If thou which lov'st all, canst love any best)
|    Thou wilt not leave me in the middle street,
|    Though some more spruce companion thou dost meet;
|    Not though a captain do come in thy way,
|    Bright parcel gilt,^[40] with forty dead men's pay;
|    Not though a brisk, perfum'd, pert courtier
|    Deign with a nod thy courtesy to answer;
|    Nor come a velvet Justice with a long
|    Great train of blue-coats [_servants_], twelve or fourteen strong,
|    Wilt thou grin or fawn on him, or prepare
|    A speech to court his beauteous son and heir.
|    For better or worse take me, or leave me:
|    To take and leave me is adultery.
|    Oh, monstrous, superstitious puritan [_purist_],
|    Of refin'd manners, yet ceremonial man,
|    That when thou meet'st one, with enquiring eyes
|    Dost search, and like a needy broker, 'prise [_appraise_]
|    The silk and gold he wears, and to that rate
|    So high or low, dost raise thy formal hat;
|    That wilt consort none until thou have known
|    What lands he hath in hope, or of his own,
|    As though all thy companions should make thee
|    Jointures,^[41] and marry thy dear company.
|    Why shouldst thou (that dost not only approve,
|    But in rank^[42] itchy lust, desire and love
|    The nakedness and bareness to enjoy,
|    Of thy plump muddy^[43] whore, prostitute boy).
|    Hate virtue, though she be naked and bare?
|    At birth and death our bodies naked are;
|    And till our souls be unapparellèd
|    Of bodies, they from bliss are banishèd.
|    Man's first blest state was naked; when by sin
|    He lost that, he was cloth'd but in beasts' skin^[44] ;
|    And in this coarse attire which I now wear,
|    With God, and with the muses I confer.
|    But since thou, like a contrite penitent,
|    Charitably warn'd of thy sins, dost repent^[45]
|    These vanities and giddinesses, lo,
|    I shut my chamber door, and come, let's go!
|    But sooner may a cheap whore, who hath been
|    Worn by as many several men in sin
|    As are black feathers, or musk-colour hose,^[46]
|    Name her child's right true father, 'mongst all those;
|    Sooner may one guess who shall bear away
|    Th' Infant^[47] of London, heir t' an India^[48];
|    And sooner may a gulling weather spy^[49]
|    By drawing forth heaven's scheme [_a horoscope_] tell certainly
|    What fashion'd hats, or ruffs, or suits next year
|    Our subtle-witted antic youths will wear,
|    Than thou, when thou depart'st from me, can show
|    Whither, why, when, or with whom thou wouldst go.
|    But how shall I be pardon'd my offence,
|    That thus have sinn'd against my conscience?
|    Now we are in the street; he first of all,
|    Improvidently proud, creeps to the wall,^[50]
|    And so imprison'd and hemm'd in by me,
|    Sells for a little state [_status_] his liberty;
|    Yet though he cannot skip forth now to greet
|    Every fine silken painted fool we meet,
|    He them to him with amorous smiles allures,
|    And grins, smacks, shrugs, and such an itch endures
|    As 'prentices, or schoolboys, which do know
|    Of some gay sport abroad, yet dare not go.
|    And as fiddlers stop lowest^[51] at highest sound,
|    So to the most brave^[52] stoops he nigh'st the ground.
|    But to a grave man he doth move no more
|    Than the wise politic horse would heretofore,
|    Or thou, O elephant or ape, wilt do
|    When any names the King of Spain to you.^[53]
|    Now leaps he upright, jogs me, and cries, ``do you see
|    Yonder well-favour'd youth"? ``Which"? ``Oh, 'tis he
|    That dances so divinely"; ``Oh," said I,
|    ``Stand still, must you dance here for company"?
|    He droop'd, we went, till one which did excel
|    Th'Indians in drinking [_inhaling_] his tobacco well
|    Met us; they talk'd; I whisper'd, ``Let us go,
|    ``'T may be you smell him not, truly I do."
|    He hears not me, but on the other side
|    A many-colour'd peacock [_dandy_] having spied,
|    Leaves him and me; I for my lost sheep stay;
|    He follows, overtakes, goes on the way,
|    Saying, ``Him whom I last left, all repute [_judge_]
|    For his device [_expertise_] in handsoming [_adorning_] a suit,
|    To judge of lace, pink, panes, print, cut,^[54] and pleat,
|    Of all the court to have the best conceit [_judgement_]."
|    ``Our dull comedians want him^[55] : let him go;
|    But oh, God strengthen thee, why stop'st thou so"?
|    ``Why? He hath travell'd," ``Long"? ``No, but to me
|    Which understand none, he doth seem to be
|    Perfect French, and Italian." I replied,
|    ``So is the pox."^[56] He answer'd not, but spied
|    More men of sort, of parts, and qualities.
|    At last his love he in a window spies,
|    And like light dew exhal'd,^[57] he flings from me,
|    Violently ravish'd to his lechery.
|    Many were there, he could command^[58] no more;
|    He quarrell'd, fought, bled; and turn'd out of door,
|    Directly came to me, hanging the head,^[59]
|    And constantly a while must keep his bed.

## William Habington: In Praise of London in the Long Vacation

From ``To My Worthy Cousin Mr E.C.^[**Mr E.C.** has not been identified.] : In Praise of the City Life in the Long Vacation," in _Castara_ (1634)

|    [...] But now it's Long Vacation^[**Long Vacation**: the period when the London law courts were closed, from late July to early October.] you will say
|    The town is empty and who ever may
|    To th' pleasure of his country home repair,
|    Fly from th' infection of our London air.^[**th' infection ... air**: before the development of the germ theory of disease transmission in C19th, contagion was thought to be carried by noxious vapour or `bad air' (miasma).]
|    In this your error. Now's the time alone
|    To live here, when the city dame is gone
|    T' her house at Brandford,^[**Brandford**: an alternative name for Brentford in Essex, a town eight miles from Charing Cross, which was popular among Londoners for rural outings.] for beyond that she
|    Imagines there's no land but Barbary,^[**Barbary**: the coast of North Africa, regarded as alien land; there is a pun on `barbarism.']
|    Where lies her husband's factor [_agent_]. When from hence
|    Rid is the country Justice, whose nonsénse
|    Corrupted had the language of the Inn,^[**Inn**: one of the Inns of Court, where barristers practised.]
|    Where he and his horse litter'd [_lodged_]. We begin
|    To live in silence, when the noise o'th' Bench
|    Not deafens Westminster, nor corrupt French^[**corrupt French**: legal jargon inherited from the (French-speaking) Normans.]
|    Walks Fleet Street in her gown.^[**Walks ... gown**: taints what is published. (**Fleet Street** had long been the domain of publishers and printers.)] Ruffs of the Bar
|    By the vacation's pow'r translated are
|    To cutwork bands.^[**Ruffs of the Bar ... cutwork bands**: Barristers' formal starched and pleated neckwear (**ruffs**) give place in the vacation to everyday collars with openwork embroidery or lace.] And who were busy here
|    Are gone to sow sedition in the shire.
|    The air by this is purg'd, and the Term's strife
|    Thus fled the city. We the civil life
|    Lead happily. When in the gentle way
|    Of noble mirth, I have the long-liv'd day
|    Contracted to a moment, I retire
|    To my Castara, and meet such a fire
|    Of mutual love, that if the city were
|    Infected, that^[**that**: i.e. their **fire/Of mutual love**.] would purify the air.

## DRAMA AND THE THEATRE {-}

## Philip Stubbes: Puritan Objections to Stage Plays

From ``Of Stage Plays and Interludes with Their Wickedness," in _The Anatomy of Abuses_ (1583)

选自菲利蒲·斯塔布斯《陋习的解剖》

## \index{Shakespeare}Shakespeare: ``On Your Imaginary Forces Work"

From _Henry V_, Prologue to Act 1 (perf. 1599)

选自莎士比亚《亨利五世》

## \index{Shakespeare}Shakespeare: The Best Actors Are but Shadows

From _A Midsummer Night's Dream_, Act 5, Sc. 1 (perf. 1595/96)

选自莎士比亚《仲夏夜之梦》

## Thomas Nashe: ``Adieu, Farewell, Earth's Bliss"

``Song," in _Summers' Last Will and Testament_ (1600) (written 1592)

选自托马斯·纳什《夏天最后的遗嘱》

## \index{Dekker, Thomas}Thomas Dekker: The Plague and Its Victims in 1603

From _The Wonderful Year_ (1603)

选自托马斯·德克的小册子

## THE COURT AND COURTIERS {-}

## Sir John Davies: ``Our Glorious English Court's Divine Image"

_Orchestra: A Poem of Dancing_ (1622) (written c. 1594)

|    Her brighter dazzling beams of majesty
|    Were laid aside, for she vouchsaf'd awhile
|    With gracious, cheerful, and familiar eye
|    Upon the revels of her court to smile,
|    For so Time's journeys she doth oft beguile,
|        Like sight no mortal eye might elsewhere see
|        So full of state, art, and variety.
|
|    For of her barons brave and ladies fair,
|    Who had they been elsewhere most fair had been,
|    Many an incomparable lovely pair
|    With hand in hand were interlinkèd seen,
|    Making fair honour to their sov'reign Queen;
|        Forward they pac'd, and did their pace apply
|        To a most sweet and solemn melody.
|
|    So subtle and so curious^[**curious**: exquisite.] was the measure,
|    With such unlook'd-for change in every strain,
|    As that Penelope, rapt with sweet pleasure,
|    Ween'd^[**Ween'd**: believed.] she beheld the true proportion plain
|    Of her own web, weav'd and unweav'd again,^[**her own web ... again**: When Penelope, faithful to her absent husband Odysseus, is importuned by many suitors, she refuses to re-marry until she has woven a shroud for her dead father-in-law. She weaves it during the day but unravels her work every night so that her task is never completed.]
|        But that her art was somewhat less, she thought,
|        And on a mere ignoble subject wrought.

|    For here, like to the silkworm's industry,
|    Beauty itself out of itself did weave
|    So rare a work and of such subtlety
|    As did all eyes entangle and deceive,
|    And in all minds a strange impression leave:
|        In this sweet labyrinth did Cupid stray,
|        And never had the power to pass away.

## Edmund Spenser: Another View of Love at Court

From _Colin Clout's Come Home Again_ (1595) (written 1590--1591), 771--94 [@Spenser1966]

选自埃德蒙·斯宾塞的诗

## Anon.: A Courtier

From ``A Courtier," in Sir Thomas Overbury, _Characters, or, Witty Descriptions of the Properties of Sundry Persons_ (1614), No. [5] (attrib.)

## \index{Dekker, Thomas}Thomas Dekker: ``How a Young Gallant Should Behave Himself in an Ordinary"

From _The Gull's Hornbook_ [dupe's primer] (1609), ch. 5

选自托马斯·德克《笨人初级读本》

## WHO SHOULD 'SCAPE WHIPPING? {-}

## \index{Earle, John}John Earle: A Shopkeeper

From ``A Shopkeeper," in _Micro-cosmography, or, a Piece of the World Discovered_. 5th ed. (1629), No. 70

## \index{Middleton, Thomas}Thomas Middleton: A Goldsmith Gulled

From _A Chaste Maid in Cheapside_, Act 1, Sc. 1 (1630) (perf. 1613)

选自托马斯·米德尔顿的戏剧

## Barnabe Rich: Vanity Fair

From _The Honesty of the Age_ (1614)

## Thomas Harman: An Abraham Man

From _A Caveat or Warning for Common Cursitors Vulgarly Called Vagabonds_ (1573), ch. 9 (first known publication 1567)

## Robert Greene: Beware of Pickpockets

From _The Second and Last Part of Coney-Catching_ [@Greene1591]

## \index{Middleton, Thomas}Middleton: Roaring Girls

From _The Roaring Girl, or, Moll Cutpurse_, Prologue (1611) (perf. ?1604--1608)

选自米德尔顿《咆哮女郎》（与\index{Dekker, Thomas}托马斯·德克合著）

## Ben Jonson: Pickpockets at Bartholomew Fair

From _Bartholomew Fair_, Act 3, Sc. 5 (1640) (perf. 1614)

选自本·琼生《巴托罗缪市集》

\begin{drama*}
\speaker{Cokes}Sister, I am an ass, I cannot keep my purse. \direct{He shows it again.} On, on; I pray thee, friend.\\
\speaker{Winwife}Will you see sport? Look, there's a fellow gathers up to him, mark.\\
\direct{Edgeworth gets up to him and tickles him in the ear with a straw twice to draw his hand out of his pocket.}
\speaker{Quarlous}Good, i'faith! O, he has lighted on the wrong pocket.\\
\speaker{Winwife}He has it, 'fore God, he is a brave fellow; pity he should be detected.\\
\speaker{Nightingale}But O, you vile nation of cutpurses all,\\
Relent and repent, and amend and be sound,\\
And know that you ought not, by honest men's fall,\\
Advance your own fortunes, to die above ground,\\
\hspace{\leftmargini}And though you go gay,\\
\hspace{\leftmargini}In silks as you may,\\
It is not the high way to heaven (as they say).\\
Repent then, repent you, for better, for worse:\\
And kiss not the gallows for cutting a purse.\\
Youth, youth, thou hadst better been starved by thy nurse,\\
Than live to be hanged for cutting a purse.\\
\speaker{All}An excellent ballad! An excellent ballad!\\
\speaker{Edgeworth}Friend, let me ha' the first, let me ha' the first, I pray you.\\
\speaker{Cokes}Pardon me, sir. First come, first served; and I'll buy the whole bundle too.\\
\speaker{Winwife}That conveyance was better than all, did you see't? He has given the purse to the ballad singer.\\
\speaker{Quarlous}Has he?\\
\speaker{Edgeworth}Sir, I cry you mercy; I'll not hinder the poor man's profit: I pray you, mistake me not.\\
\speaker{Cokes}Sir, I take you for an honest gentleman, if that be mistaking. I met you today afore: ha! Hum'h! O God! my purse is gone, my purse, my purse, etc.\\
\end{drama*}

## \index{Earle, John}John Earle: A Prison

From ``A Prison," in _Micro-cosmography, or, A Piece of the World Discovered_. 5th ed. (1629), No. [12]

## \index{Lupton, Donald}Donald Lupton: Bedlam

From ``Bedlam," in _London and the Country Carbonadoed and Quartered_ (1632), Part 1, No. 19

见 \@ref(lupton)

## \index{Dekker, Thomas}Dekker and \index{Middleton, Thomas}Middleton: Entertainment Provided by the Inmates of Bedlam

From _The Honest Whore_, Part I, [Act 5, Sc. 2] (1604)

选自德克和米德尔顿《诚实的妓女》

## THE COMING OF THE COMMONWEALTH {-}

## Andrew Marvell: The Execution of Charles I

``An Horatian Ode upon Cromwell's Return from Ireland," in _Miscellaneous Poems_ (1681) (written 1650).

安德鲁·马维尔的诗

|    [...] That thence^[**thence**: from Carisbrooke Castle on the Isle of Wight, where Charles had been imprisoned.] the royal actor borne
|    The tragic scaffold^[**scaffold**: (1) a platform for executions (in this case erected for Charles outside the Banqueting House in Whitehall Palace, a fine Palladian building with its Rubens ceiling, commissioned by Charles, celebrating his father's rule); (2) stage.] might adorn,
|        While round the armèd bands
|        Did clap their bloody hands.^[**Did clap their ... hands**: not in applause, but in an attempt to drown out his speech from the scaffold.]
|
|    He nothing common did or mean
|    Upon that memorable scene:
|        But with his keener eye
|        The axe's edge did try;
|
|    Nor called the gods with vulgar spite
|    To vindicate his helpless right,
|        But bowed his comely head
|        Down as upon a bed.
|
|    This was that memorable hour
|    Which first assur'd the forcèd^[**forcèd**: gained and maintained by force.] power:
|        So when they did design
|        The Capitol's first line,
|
|    A Bleeding Head, where they begun,
|    Did fright the architects to run;
|        And yet in that the State
|        Foresaw its happy fate!^[**The Capitol's ... fate**: the Capitol was the great temple of Jupiter in Rome, so called because digging its foundations unearthed a human head (Latin caput), which was interpreted as a good omen for Rome's destiny.]

## \index{Evelyn, John}John Evelyn: ``The Funeral Sermon of Preaching" {#evelyn}

From his _Diary_ (or _Kalendarium_) on 30 December 1655

选自约翰·伊夫林《日记》

## \index{Evelyn, John}Evelyn: Persecution of Royalist Churchgoers

From his _Diary_ (or _Kalendarium_) on 25 December 1657

见 \@ref(evelyn)
