# Period 2: London in the Enlightenment (1660--1780)

## Celia Fiennes: Some Topographical Features of London

From _Through England on a Side Saddle in the Time of William and Mary_ (1888) (written 1703)

## \index{Defoe, Daniel}Daniel Defoe: London Surging in Size {#defoe}

From _A Tour Through the Whole Island of Great Britain_ (1724--1726), Vol. 2, Letter 2

选自丹尼尔·笛福《不列颠全岛纪游》

## THE RESTORATION {-}

## \index{Evelyn, John}John Evelyn: Charles II's Triumphal Entry into London {#evelyn-diary}

His Diary on 29 May 1660

约翰·伊夫林的日记

## \index{Evelyn, John}Evelyn: Bodies of Cromwell and Others Exhumed

His Diary on 30 January 1661

见 \@ref(evelyn-diary)

## \index{Evelyn, John}Evelyn: Gambling and Debauchery at the Court of Charles II

His Diary on 6 January 1662

见 \@ref(evelyn-diary)

## \index{Evelyn, John}Evelyn: James II's Ill-Timed Feast for the Venetian

His Diary on 18 December 1685

见 \@ref(evelyn-diary)

## THE GREAT PLAGUE {-}

## \index{Pepys, Samuel}Samuel Pepys Describes the Plague {#pepys-diary}

His Diary on 3 September 1665 and 14 September 1665

塞缪尔·佩皮斯的日记

## \index{Defoe, Daniel}Daniel Defoe's Imaginative Reconstruction of the Great Plague

From _A Journal of the Plague Year_ (1722)

选自丹尼尔·笛福《大疫年日记》

## THE GREAT FIRE {-}

## John Dryden: London on Fire

From _Annus Mirabilis: The Year of Wonders, 1666_ (1667)

选自约翰·德莱顿《奇异的年代》

\setlength{\beforepoemtitleskip}{0.3ex}
\setlength{\afterpoemtitleskip}{0.2ex}
\settowidth{\versewidth}{Such was the rise of this prodigious fire,}

\poemtitle*{215\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Such was the rise of this prodigious fire,\\*
Which in mean buildings first obscurely bred,\\*
From thence did soon to open streets aspire,\\*
And straight to palaces and temples spread.
\end{altverse}
\end{verse}

\poemtitle*{216\\*}
\begin{verse}[\versewidth]
\begin{altverse}
The diligence of trades and noiseful gain,\\*
And luxury, more late,\footnote{\textbf{more late}: later to bed than honest tradesmen.} asleep were laid;\\*
All was the night's, and in her silent reign,\\*
No sound the rest of nature did invade.
\end{altverse}
\end{verse}

\poemtitle*{217\\*}
\begin{verse}[\versewidth]
\begin{altverse}
In this deep quiet, from what source unknown,\\*
Those seeds of fire their fatal birth disclose;\\*
And first, few scattering sparks about were blown,\\*
Big\footnote{\textbf{Big}: pregnant.} with the flames that to our ruin rose.
\end{altverse}
\end{verse}

\poemtitle*{218\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Then, in some close-pent room it crept along,\\*
And smouldering as it went, in silence fed;\\*
Till th'infant monster, with devouring strong,\\*
Walked boldly upright with exalted head.
\end{altverse}
\end{verse}

\poemtitle*{219\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Now, like some rich or mighty murderer,\\*
Too great for prison, which he breaks with gold;\\*
Who fresher for new mischiefs does appear,\\*
And dares the world to tax him with the old.
\end{altverse}
\end{verse}

\poemtitle*{220\\*}
\begin{verse}[\versewidth]
\begin{altverse}
So 'scapes th'insulting\footnote{\textbf{insulting}: (1) leaping friskily; (2) attacking.} fire his narrow gaol,\\*
And makes small outlets into open air;\\*
There the fierce winds his open force assail,\\*
And beat him downward to his first repair.
\end{altverse}
\end{verse}

\poemtitle*{221\\*}
\begin{verse}[\versewidth]
\begin{altverse}
The winds, like crafty courtesans, withheld\\*
His flames from burning, but to blow them more;\\*
And, every fresh attempt, he is repell'd\\*
With faint denials, weaker than before.
\end{altverse}
\end{verse}

\poemtitle*{222\\*}
\begin{verse}[\versewidth]
\begin{altverse}
And now, no longer letted {[}\emph{hindered}{]} of his prey,\\*
He leaps up at it with enrag'd desire;\\*
O'erlooks the neighbours with a wide survey,\\*
And nods at every house his threatening fire.
\end{altverse}
\end{verse}

\poemtitle*{223\\*}
\begin{verse}[\versewidth]
\begin{altverse}
The ghosts of traitors from the Bridge\footnote{\textbf{The ghosts \ldots{} Bridge}: The heads of traitors were displayed on spikes on London \textbf{Bridge}.} descend,\\*
With bold fanatic spectres to rejoice;\\*
About the fire into a dance they bend,\\*
And sing their Sabbath\footnote{\textbf{Sabbath}: (1) Sunday, when the fire broke out, just after midnight; (2) ``A midnight meeting of demons, sorcerers and witches, presided over by the Devil" (\emph{OED}).} notes with feeble voice {[}\ldots{}{]}
\end{altverse}
\end{verse}

\poemtitle*{255\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Those who have homes, when home they do repair\\*
To a last lodging call their wandering friends.\\*
Their short uneasy sleeps are broke with care,\\*
To look how near their own destruction tends.
\end{altverse}
\end{verse}

\poemtitle*{256\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Those who have none sit round where once it was,\\*
And with full eyes each wonted room require;\\*
Haunting the yet warm ashes of the place,\\*
As murder'd men walk where they did expire.
\end{altverse}
\end{verse}

\poemtitle*{257\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Some stir up coals and watch the Vestal\footnote{\textbf{Vestal}: Vesta was the ancient Roman goddess of the hearth.} fire,\\*
Others in vain from sight of ruin run;\\*
And while through burning labyrinths they retire,\\*
With loathing eyes repeat what they would shun.
\end{altverse}
\end{verse}

\poemtitle*{258\\*}
\begin{verse}[\versewidth]
\begin{altverse}
The most, in fields, like herded beasts lie down;\\*
To dews obnoxious\footnote{\textbf{To dews obnoxious}: exposed to {[}harmful{]} damp.} on the grassy floor;\\*
And while their babes in sleep their sorrows drown,\\*
Sad parents watch the remnants of their store.
\end{altverse}
\end{verse}

\poemtitle*{259\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Now, like some rich or mighty murderer,\\*
Too great for prison, which he breaks with gold;\\*
Who fresher for new mischiefs does appear,\\*
And dares the world to tax him with the old.
\end{altverse}
\end{verse}

\poemtitle*{275\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Nor could thy fabric, Paul's, defend thee long,\\*
Though thou wert sacred to thy Maker's praise;\\*
Though made immortal by a poet's song\footnote{\textbf{Though made \ldots{} song}: Referring to Edmund Waller's poem ``Upon His Majesty's Repairing of Paul's" (1645).};\\*
And poets' songs the Theban walls could raise.\footnote{\textbf{And poets' songs \ldots{} raise}: Referring to the harpist Amphion in Greek mythology, whose music drew stones together to build the walls of Thebes." (1645).}
\end{altverse}
\end{verse}

\poemtitle*{276\\*}
\begin{verse}[\versewidth]
\begin{altverse}
The daring flames peep'd in and saw from far,\\*
The awful beauties of the sacred choir;\\*
But, since it was profan'd by Civil War,\footnote{\textbf{profaned by Civil War}: Cromwell used the nave as cavalry barracks; the iconoclastic Parliamentarians severely damaged effigies, woodwork, and windows.}\\*
Heaven thought it fit to have it purg'd by fire.
\end{altverse}
\end{verse}

\poemtitle*{277\\*}
\begin{verse}[\versewidth]
\begin{altverse}
Now down the narrow streets it swiftly came,\\*
And widely opening, did on both sides prey.\\*
This benefit we sadly owe the flame,\\*
If only ruin must enlarge our way.
\end{altverse}
\end{verse}

\poemtitle*{278\\*}
\begin{verse}[\versewidth]
\begin{altverse}
And now four days the sun had seen our woes,\\*
Four nights the moon beheld th'incessant fire;\\*
It seemed as if the stars more sickly rose,\\*
And farther from the feverish north retire.
\end{altverse}
\end{verse}

\poemtitle*{279\\*}
\begin{verse}[\versewidth]
\begin{altverse}
In th'émpyrean Heav'n (the bless'd abode)\\*
The Thrones and the Dominions\footnote{\textbf{Thrones and Dominions}: two of the nine orders of angels.} prostrate lie,\\*
Not daring to behold their angry God;\\*
And an hush'd silence damps the tuneful sky.
\end{altverse}
\end{verse}

\poemtitle*{280\\*}
\begin{verse}[\versewidth]
\begin{altverse}
At length th'Almighty cast a pitying eye,\\*
And mercy softly touch'd his melting breast;\\*
He saw the town's one half in rubbish lie,\\*
And eager flames give on to storm the rest.
\end{altverse}
\end{verse}

\poemtitle*{281\\*}
\begin{verse}[\versewidth]
\begin{altverse}
An hollow crystal pyramid he takes,\\*
In firmamental waters dipp'd above;\\*
Of it a broad extinguisher he makes,\\*
And hoods the flames that to their quarry strove.
\end{altverse}
\end{verse}

\poemtitle*{282\\*}
\begin{verse}[\versewidth]
\begin{altverse}
The vanquish'd fires withdraw from every place,\\*
Or full with feeding, sink into a sleep;\\*
Each household Genius\footnote{\textbf{Genius}: tutelary deity.} shows again his face,\\*
And from the hearths the little Lares\footnote{\textbf{Lares}: gods of the household in Roman mythology.} creep.
\end{altverse}
\end{verse}

## \index{Pepys, Samuel}Pepys' Buried Treasures

His Diary on 4 September 1666

见 \@ref(pepys-diary)

## \index{Defoe, Daniel}Defoe: London Before and After the Fire

From _A Tour Through the Whole Island of Great Britain_ (1724--1726), Vol. 2, Letter 2

见 \@ref(defoe)

## INSTITUTIONS {-}

## \index{Evelyn, John}John Evelyn: Some Unusual Proceedings of the Royal Society

His Diary on 5 April 1682 and 12 April 1682

见 \@ref(evelyn-diary)

## \index{Ward, Ned}Ned Ward: The Rebuilding of St Paul's Cathedral {#ward}

From _The London Spy_ (1698--1709), Part 5

内德·沃德，又名爱德华·沃德

## Joseph Addison: The Royal Exchange

From _The Spectator_, No. 69 (19 May 1711)

选自约瑟夫·艾迪生《旁观者》杂志

## \index{Ward, Ned}Ned Ward: Crowds at the Entrance to the Royal Exchange

From _The London Spy_ (1698--1709), Part 3

见 \@ref(ward)

## \index{Defoe, Daniel}Defoe: Westminster Abbey

From _A Tour Through the Whole Island of Great Britain_ (1724--1726), Vol. 2, Letter 2

见 \@ref(defoe)

## ALL THAT LIFE CAN AFFORD {-}

## \index{Johnson, Samuel}Samuel Johnson in Praise of London

见 [@Boswell2008]

## \index{Gay, John}John Gay: The Labyrinthine Streets of London {#gay}

From _Trivia, or, The Art of Walking the Streets of London_ (1716), Bk 2

选自约翰·盖伊《琐事》

|    Where fam'd Saint Giles's ancient limits spread,
|    An inrail'd^[**inrailed**: enclosed by railings.] column rears its lofty head.
|    Here to seven streets, seven dials [_clocks_] count the day,
|    And from each other catch the circling ray.
|    Here oft the peasant, with enquiring face,
|    Bewilder'd, trudges on from place to place;
|    He dwells on every sign with stupid [_stupefied_] gaze,
|    Enters the narrow alley's doubtful maze,
|    Tries every winding court and street in vain,
|    And doubles o'er his weary steps again.
|    Thus hardy Theseus,^[**Theseus**: mythical founder of Athens. He entered the baffling maze or `Labyrinth' of Crete to slay its occupant, the Minotaur, a fearsome bull-man monster to whom Athenian virgins were being sacrificed.] with intrepid feet,
|    Travers'd the dang'rous Labyrinth of Crete;
|    But still the wand'ring passes forced his stay,^[**wandering passes forced his stay**: winding passages brought him to a halt.]
|    Till Ariadne's clue^[**clue**: or `clew'; a ball of yarn or thread. The Cretan princess Ariadne gave Theseus a ball of thread with which (by unravelling it) he traced his way into (and thus safely out of) the Labyrinth. This story is the origin of the modern sense of clue as ``guide, pointer, hint.""] unwinds the way.
|    But do not thou, like that bold chief, confide [_trust_]
|    Thy vent'rous footsteps to a female guide;
|    She'll lead thee, with delusive smiles along,
|    Dive in thy fob,^[**fob**: ``A small pocket formerly made in the waistband of the breeches and used for carrying a watch, money, or other valuables" (_OED_).] and drop thee in the throng.

## \index{Gay, John}Gay on Pall Mall

From _Trivia, or, The Art of Walking the Streets of London_ (1716), Bk 2

见 \@ref(gay)

|    O bear me to the paths of fair Pell Mell,
|    Safe are thy pavements, grateful [_pleasing_] is thy smell!
|    At distance, rolls along the gilded coach,
|    Nor sturdy carmen [_carters_] on thy walks encroach;
|    No lets [_hindrances_] would bar thy ways, were chairs^[**chairs**: sedan chairs, enclosed litters carried on horizontal poles by two bearers; they were either private (a lady could be carried about the crowded streets in privacy and cleanliness by her servants) or for public hire. As status-symbols they were **supports of ... Pride**, having right of way over mere pedestrians.] denied ---
|    The soft supports of Laziness and Pride;
|    Shops breath perfumes, through sashes ribbons glow,
|    The mutual arms of ladies and the beau.
|    Yet still even here, when rains the passage hide,
|    Oft the loose stone spirts up a muddy tide
|    Beneath thy careless foot; and from on high,
|    Where masons mount the ladder, fragments fly;
|    Mortar and crumbled lime in showers descend,
|    And o'er thy head destructive tiles impend [_hang_].

## Jonathan Swift: ``A Description of a City Shower"

From _The Tatler_ (1710), No. 238

乔纳森·斯威夫特，选自《闲谈者》杂志

## Tobias Smollett: Ranelagh and Vauxhall Gardens

From _The Expedition of Humphry Clinker_. 2nd ed. 3 vols. (1771), Vol. 1

选自托比亚斯·斯摩莱特《亨佛利·克林克》

## Hannah More: The Bluestocking Circle

A letter of hers in _Memoirs of the Life and Correspondence of Hannah More_, ed. William Roberts (1834) (written 1775)

汉纳·莫尔的一封信

## \index{Ward, Ned}Ned Ward: Pork Sellers at Bartholomew Fair

From _The London Spy_ (1698--1709), Part 10

见 \@ref(ward)

## Benjamin Franklin: ``Work, the Curse of the Drinking Classes"

From _Autobiography_ (1793), ch. 6

选自本杰明·富兰克林《富兰克林自传》

## A WALK ON THE WILD SIDE {-}

## \index{Gay, John}John Gay: Perils of London by Night

From _Trivia, or, The Art of Walking the Streets of London_ (1716), Bk 3

见 \@ref(gay)

|    Though you through cleanlier alleys wind by day,
|    To shun the hurries of the public way,
|    Yet ne'er to those dark paths by night retire;
|    Mind only safety, and condemn the mire.
|    Then no impervious courts thy haste detain,
|    Nor sneering ale-wives bid thee turn again.
|
|    Where Lincoln's Inn, wide space,^[**Lincoln's Inn, wide space**: **Lincoln's Inn** Fields was for centuries London's largest square. While there were fashionable houses beyond its surrounding railings, robbers and petty criminals made the open space unsafe.] is rail'd around
|    Cross not with vent'rous step; there oft is found
|    The lurking thief, who while the daylight shone
|    Made the walls echo with his begging tone;
|    That crutch which late compassion mov'd shall wound
|    Thy bleeding head and fell thee to the ground.
|    Though thou art tempted by the link man's call,^[**link man's call**: men with torches offered to light people's way in dark areas for a fee.]
|    Yet trust him not along the lonely wall;
|    In the mid-way he'll quench the flaming brand,
|    And share the booty with the pilf'ring band.
|    Still keep the public streets, where oily rays
|    Shot from the crystal lamp o'erspread the ways.

## James Smith: Sex-Workers in the Strand

_The Art of Living in London_ (1768), Canto 2

|    As through the streets, O Virtue, as I go,
|    Shield me from one that's equally my foe;
|    Who _cap-à-pie_, like Hamlet's ghost now stalks,
|    And makes “night hideous” by her nightly walks.^[**Who _cap-à-pie_ ... walks**: in her alluring make-up and attire she is like Hamlet's father's ghost, who is armed for combat **_cap-à-pie_** (`from head to foot', _Hamlet_ 1.2.200), and whose walking makes **``night hideous"** (1.4.54).]
|    How can the Muse without a sigh proclaim,
|    And tell that ``woman" is this monster's^[**monster**: unnatural creature.] name;
|    Woman, man's chiefest good, by Heaven design'd
|    To glad the heart, and humanize the mind;
|    To soothe each angry care, abate each strife,
|    And lull the passions as we walk through life;
|    But fall'n from such a height, so very low,
|    She now has nothing but her form to show;
|    A scandal to that sex she was before;
|    Each grace polluted by the name of W---e.
|
|    How shall I speak of all the various arts
|    She nightly uses to entrap our hearts?
|    How shall I paint the loose, familiar airs,
|    Affected speeches, and immodest leers
|    Of all these midnight daughters as they stand,
|    In shameless groups along the lengthened Strand?
|    Lost to all thought -- remote from every sense
|    Of female decency or innocence;
|    Disrob'd of all restraint or modest port,
|    Here Prostitution holds her public court.
|    With flaunting strides, and affectation's eye,
|    Behold these sycophants in love pass by [...]
|    O! purchased love, retail'd through all the town,
|    Where each may share on paying half a crown^[**half a crown**: two shillings and sixpence, or about £15 in 2018 terms.];
|    Where every air of tenderness is art,
|    And not one word, the language of the heart;
|    Where all this mockery of Cupid's reign
|    Ends in remorse, in wretchedness, and pain [_i.e. of venereal disease_].

## \index{Defoe, Daniel}Daniel Defoe on Shoplifting {#moll-flanders}

From _The Fortune and Misfortunes of the Famous Moll Flanders_ (1722)

选自丹尼尔·笛福《摩尔·弗兰德斯》

## \index{Defoe, Daniel}Defoe: Newgate Prison

From _The Fortune and Misfortunes of the Famous Moll Flanders_ (1722)

见 \@ref(moll-flanders)

## Samuel Richardson: An Execution at Tyburn

From _The Complete Letter-Writer: Or, Polite English Secretary_ (8th edition, 1762), pp. 207--9

塞缪尔·理查逊

## \index{Johnson, Samuel}Samuel Johnson: The Crime of Poverty

From _London: A Poem in Imitation of the Third Satire of Juvenal_ (1738)

塞缪尔·约翰逊

\settowidth{\versewidth}{By numbers here from shame or censure free,}
\begin{verse}[\versewidth]
By numbers here from shame or censure free,\\
All crimes are safe but hated poverty.\\
This, only this, the rigid law pursues;\\
This, only this, provokes the snarling Muse.\\
The sober trader at a tatter'd cloak\footnote{\textbf{at a tatter'd cloak}: i.e. on seeing a sign of poverty.}\\
Wakes from his dream, and labours for a joke;\\
With brisker air the silken courtiers gaze,\\
And turn the varied taunt a thousand ways.\\
Of all the griefs that harass the distress'd,\\
Sure, the most bitter is a scornful jest;\\
Fate never wounds more deep the gen'rous heart,\\
Than when a blockhead's insult points the dart.\\!
Has Heaven reserv'd, in pity to the poor,\\
No pathless waste, or undiscover'd shore?\\
No secret island in the boundless main?\\
No peaceful desert yet unclaim'd by Spain?\\
Quick let us rise, the happy seats explore,\\
And bear oppression's insolence no more.\\
This mournful truth is ev'rywhere confess'd,\\
\textsc{Slow rises worth, by poverty depress'd.}\\
But here more slow, where all are slaves to gold,\\
Where looks are merchandise, and smiles are sold;\\
Where won by bribes, by flatteries implor'd,\\
The groom retails the favours of his lord.
\end{verse}

## Thomas Holcoft: The Gordon Riots

From _A Plain and Succinct Narrative of the Late Riots and Disturbances_ (1780)
